<#macro page>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Doka - Sign In/Up</title>
        <link href="/webjars/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
    <div class="container">

        <#nested>

    </div>

    </body>
    </html>

</#macro>